package cn.lhrj.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("jy_accept_parts", "id", JyAcceptParts.class);
		arp.addMapping("jy_accept_process", "id", JyAcceptProcess.class);
		arp.addMapping("jy_accept_product", "id", JyAcceptProduct.class);
		arp.addMapping("jy_client", "client_id", JyClient.class);
		arp.addMapping("jy_order", "id", JyOrder.class);
		arp.addMapping("jy_parts", "parts_id", JyParts.class);
		arp.addMapping("jy_plant", "id", JyPlant.class);
		arp.addMapping("jy_principal", "principal_id", JyPrincipal.class);
		arp.addMapping("jy_process", "process_id", JyProcess.class);
		arp.addMapping("jy_product", "product_id", JyProduct.class);
		arp.addMapping("jy_repertory", "id", JyRepertory.class);
		arp.addMapping("jy_repertory_log", "id", JyRepertoryLog.class);
		arp.addMapping("jy_report", "id", JyReport.class);
		arp.addMapping("session", "id", Session.class);
		arp.addMapping("shop_address", "id", ShopAddress.class);
		arp.addMapping("shop_attribute", "id", ShopAttribute.class);
		arp.addMapping("shop_attribute_category", "id", ShopAttributeCategory.class);
		arp.addMapping("shop_blessing", "id", ShopBlessing.class);
		arp.addMapping("shop_brand", "id", ShopBrand.class);
		arp.addMapping("shop_category", "id", ShopCategory.class);
		arp.addMapping("shop_categoryclassfy", "id", ShopCategoryclassfy.class);
		arp.addMapping("shop_consume_log", "id", ShopConsumeLog.class);
		arp.addMapping("shop_coupon", "id", ShopCoupon.class);
		arp.addMapping("shop_coupon_goods", "id", ShopCouponGoods.class);
		arp.addMapping("shop_denomination", "id", ShopDenomination.class);
		arp.addMapping("shop_goods", "id", ShopGoods.class);
		arp.addMapping("shop_goods_attribute", "id", ShopGoodsAttribute.class);
		arp.addMapping("shop_goods_gallery", "id", ShopGoodsGallery.class);
		arp.addMapping("shop_goods_specification", "id", ShopGoodsSpecification.class);
		arp.addMapping("shop_index_img", "id", ShopIndexImg.class);
		arp.addMapping("shop_order", "id", ShopOrder.class);
		arp.addMapping("shop_order_goods", "id", ShopOrderGoods.class);
		arp.addMapping("shop_order_log", "id", ShopOrderLog.class);
		arp.addMapping("shop_order_reciver", "id", ShopOrderReciver.class);
		arp.addMapping("shop_product", "id", ShopProduct.class);
		arp.addMapping("shop_shipping", "id", ShopShipping.class);
		arp.addMapping("shop_specification", "id", ShopSpecification.class);
		arp.addMapping("shop_topic_category", "id", ShopTopicCategory.class);
		arp.addMapping("shop_user", "id", ShopUser.class);
		arp.addMapping("shop_user_coupon", "id", ShopUserCoupon.class);
		arp.addMapping("sys_area", "iid", SysArea.class);
		arp.addMapping("sys_config", "id", SysConfig.class);
		arp.addMapping("sys_dept", "dept_id", SysDept.class);
		arp.addMapping("sys_menu", "menu_id", SysMenu.class);
		arp.addMapping("sys_message", "iid", SysMessage.class);
		arp.addMapping("sys_remain", "uid", SysRemain.class);
		arp.addMapping("sys_role", "role_id", SysRole.class);
		arp.addMapping("sys_role_menu", "id", SysRoleMenu.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("task_run_log", "id", TaskRunLog.class);
		arp.addMapping("tb_token", "user_id", TbToken.class);
		arp.addMapping("upload_counter", "uploadType", UploadCounter.class);
	}
}

