package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyAcceptProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyAcceptProduct extends BaseJyAcceptProduct<JyAcceptProduct> {
	public static final JyAcceptProduct dao = new JyAcceptProduct().dao();
}
