package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyAcceptParts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyAcceptParts extends BaseJyAcceptParts<JyAcceptParts> {
	public static final JyAcceptParts dao = new JyAcceptParts().dao();
}
