package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyAcceptProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyAcceptProcess extends BaseJyAcceptProcess<JyAcceptProcess> {
	public static final JyAcceptProcess dao = new JyAcceptProcess().dao();
}
