package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyClient extends BaseJyClient<JyClient> {
	public static final JyClient dao = new JyClient().dao();
}
