package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyOrder extends BaseJyOrder<JyOrder> {
	public static final JyOrder dao = new JyOrder().dao();
}
