package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyParts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyParts extends BaseJyParts<JyParts> {
	public static final JyParts dao = new JyParts().dao();
}
