package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyPlant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyPlant extends BaseJyPlant<JyPlant> {
	public static final JyPlant dao = new JyPlant().dao();
}
