package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyPrincipal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyPrincipal extends BaseJyPrincipal<JyPrincipal> {
	public static final JyPrincipal dao = new JyPrincipal().dao();
}
