package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyProcess extends BaseJyProcess<JyProcess> {
	public static final JyProcess dao = new JyProcess().dao();
}
