package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyProduct extends BaseJyProduct<JyProduct> {
	public static final JyProduct dao = new JyProduct().dao();
}
