package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyRepertory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyRepertory extends BaseJyRepertory<JyRepertory> {
	public static final JyRepertory dao = new JyRepertory().dao();
}
