package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyRepertoryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyRepertoryLog extends BaseJyRepertoryLog<JyRepertoryLog> {
	public static final JyRepertoryLog dao = new JyRepertoryLog().dao();
}
