package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseJyReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JyReport extends BaseJyReport<JyReport> {
	public static final JyReport dao = new JyReport().dao();
}
