package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopAttributeCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopAttributeCategory extends BaseShopAttributeCategory<ShopAttributeCategory> {
	public static final ShopAttributeCategory dao = new ShopAttributeCategory().dao();
}
