package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopCoupon extends BaseShopCoupon<ShopCoupon> {
	public static final ShopCoupon dao = new ShopCoupon().dao();
}
