package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopTopicCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopTopicCategory extends BaseShopTopicCategory<ShopTopicCategory> {
	public static final ShopTopicCategory dao = new ShopTopicCategory().dao();
}
