package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopCouponGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopCouponGoods extends BaseShopCouponGoods<ShopCouponGoods> {
	public static final ShopCouponGoods dao = new ShopCouponGoods().dao();
}
