package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopCategoryclassfy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopCategoryclassfy extends BaseShopCategoryclassfy<ShopCategoryclassfy> {
	public static final ShopCategoryclassfy dao = new ShopCategoryclassfy().dao();
}
