package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopRechargeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopRechargeLog extends BaseShopRechargeLog<ShopRechargeLog> {
	public static final ShopRechargeLog dao = new ShopRechargeLog().dao();
}
