package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopProduct extends BaseShopProduct<ShopProduct> {
	public static final ShopProduct dao = new ShopProduct().dao();
}
