package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopAttribute extends BaseShopAttribute<ShopAttribute> {
	public static final ShopAttribute dao = new ShopAttribute().dao();
}
