package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopOrderReciver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopOrderReciver extends BaseShopOrderReciver<ShopOrderReciver> {
	public static final ShopOrderReciver dao = new ShopOrderReciver().dao();
}
