package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopCategory extends BaseShopCategory<ShopCategory> {
	public static final ShopCategory dao = new ShopCategory().dao();
}
