package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopOrderGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopOrderGoods extends BaseShopOrderGoods<ShopOrderGoods> {
	public static final ShopOrderGoods dao = new ShopOrderGoods().dao();
}
