package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopAddress extends BaseShopAddress<ShopAddress> {
	public static final ShopAddress dao = new ShopAddress().dao();
}
