package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopBrand extends BaseShopBrand<ShopBrand> {
	public static final ShopBrand dao = new ShopBrand().dao();
}
