package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopGoodsSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopGoodsSpecification extends BaseShopGoodsSpecification<ShopGoodsSpecification> {
	public static final ShopGoodsSpecification dao = new ShopGoodsSpecification().dao();
}
