package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopIndexImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopIndexImg extends BaseShopIndexImg<ShopIndexImg> {
	public static final ShopIndexImg dao = new ShopIndexImg().dao();
}
