package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopGoodsAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopGoodsAttribute extends BaseShopGoodsAttribute<ShopGoodsAttribute> {
	public static final ShopGoodsAttribute dao = new ShopGoodsAttribute().dao();
}
