package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopOrder extends BaseShopOrder<ShopOrder> {
	public static final ShopOrder dao = new ShopOrder().dao();
}
