package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopBlessing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopBlessing extends BaseShopBlessing<ShopBlessing> {
	public static final ShopBlessing dao = new ShopBlessing().dao();
}
