package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopSpecification extends BaseShopSpecification<ShopSpecification> {
	public static final ShopSpecification dao = new ShopSpecification().dao();
}
