package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopGoods extends BaseShopGoods<ShopGoods> {
	public static final ShopGoods dao = new ShopGoods().dao();
}
