package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopOrderLog extends BaseShopOrderLog<ShopOrderLog> {
	public static final ShopOrderLog dao = new ShopOrderLog().dao();
}
