package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopUser extends BaseShopUser<ShopUser> {
	public static final ShopUser dao = new ShopUser().dao();
}
