package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopDenomination;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopDenomination extends BaseShopDenomination<ShopDenomination> {
	public static final ShopDenomination dao = new ShopDenomination().dao();
}
