package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopUserCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopUserCoupon extends BaseShopUserCoupon<ShopUserCoupon> {
	public static final ShopUserCoupon dao = new ShopUserCoupon().dao();
}
