package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopShipping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopShipping extends BaseShopShipping<ShopShipping> {
	public static final ShopShipping dao = new ShopShipping().dao();
	
	
	public static String getCodeByid(int id) {
		String code=null;
		ShopShipping shipping=new ShopShipping().findById(id);
		if (null!=shipping) {
			return shipping.getCode();
		}
		return code;

	}
	
}
