package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseShopConsumeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopConsumeLog extends BaseShopConsumeLog<ShopConsumeLog> {
	public static final ShopConsumeLog dao = new ShopConsumeLog().dao();
}
