package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseSysDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDept extends BaseSysDept<SysDept> {
	public static final SysDept dao = new SysDept().dao();
}
