package cn.lhrj.common.model;

import java.util.List;

import cn.lhrj.common.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	public List<SysMenu> queryListParentId(long parentid) {
		List<SysMenu> menus=new SysMenu().find("select * from sys_menu where parent_id = ? AND status = 0 order by order_num asc",parentid);
		return menus;
	}
}
