package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseSysRemain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRemain extends BaseSysRemain<SysRemain> {
	public static final SysRemain dao = new SysRemain().dao();
}
