package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser().dao();
	
	public SysUser removeSensitiveInfo() {
		remove("password");
		return this;
	}
}
