package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseTaskRunLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskRunLog extends BaseTaskRunLog<TaskRunLog> {
	public static final TaskRunLog dao = new TaskRunLog().dao();
}
