package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseTbToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbToken extends BaseTbToken<TbToken> {
	public static final TbToken dao = new TbToken().dao();
}
