package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseYjParts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YjParts extends BaseYjParts<YjParts> {
	public static final YjParts dao = new YjParts().dao();
}
