package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseYjProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YjProcess extends BaseYjProcess<YjProcess> {
	public static final YjProcess dao = new YjProcess().dao();
}
