package cn.lhrj.common.model;

import cn.lhrj.common.model.base.BaseYjProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YjProduct extends BaseYjProduct<YjProduct> {
	public static final YjProduct dao = new YjProduct().dao();
}
