package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopGoodsGallery<M extends BaseShopGoodsGallery<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商品id
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 图片
	 */
	public M setImgUrl(byte[] imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public byte[] getImgUrl() {
		return get("img_url");
	}

	/**
	 * 描述
	 */
	public M setImgDesc(java.lang.String imgDesc) {
		set("img_desc", imgDesc);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getImgDesc() {
		return getStr("img_desc");
	}

	/**
	 * 排序
	 */
	public M setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}

}
