package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopCouponGoods<M extends BaseShopCouponGoods<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券Id
	 */
	public M setCouponId(java.lang.Integer couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}
	
	/**
	 * 优惠券Id
	 */
	public java.lang.Integer getCouponId() {
		return getInt("coupon_id");
	}

	/**
	 * 商品id
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

}
