package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAccountId(java.lang.Long accountId) {
		set("accountId", accountId);
		return (M)this;
	}
	
	public java.lang.Long getAccountId() {
		return getLong("accountId");
	}

	public M setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
		return (M)this;
	}
	
	public java.lang.Long getExpireAt() {
		return getLong("expireAt");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
