package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysConfig<M extends BaseSysConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 键
	 */
	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}
	
	/**
	 * 键
	 */
	public java.lang.String getKey() {
		return getStr("key");
	}

	/**
	 * 值
	 */
	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	/**
	 * 值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 编码
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 类型
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 排序号
	 */
	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	/**
	 * 更新人
	 */
	public M setUpdateId(java.lang.String updateId) {
		set("update_id", updateId);
		return (M)this;
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdateId() {
		return getStr("update_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	/**
	 * 创建者
	 */
	public M setCreateId(java.lang.String createId) {
		set("create_id", createId);
		return (M)this;
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateId() {
		return getStr("create_id");
	}

}
