package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMessage<M extends BaseSysMessage<M>> extends Model<M> implements IBean {

	public M setIid(java.lang.Long iid) {
		set("iid", iid);
		return (M)this;
	}
	
	public java.lang.Long getIid() {
		return getLong("iid");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContents(java.lang.String contents) {
		set("contents", contents);
		return (M)this;
	}
	
	public java.lang.String getContents() {
		return getStr("contents");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setLinkUrl(java.lang.String linkUrl) {
		set("link_url", linkUrl);
		return (M)this;
	}
	
	public java.lang.String getLinkUrl() {
		return getStr("link_url");
	}

	public M setIsPush(java.lang.Integer isPush) {
		set("is_push", isPush);
		return (M)this;
	}
	
	public java.lang.Integer getIsPush() {
		return getInt("is_push");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("create_user_id");
	}

	public M setPushTime(java.util.Date pushTime) {
		set("push_time", pushTime);
		return (M)this;
	}
	
	public java.util.Date getPushTime() {
		return get("push_time");
	}

	public M setPushSuccessCount(java.lang.Integer pushSuccessCount) {
		set("push_success_count", pushSuccessCount);
		return (M)this;
	}
	
	public java.lang.Integer getPushSuccessCount() {
		return getInt("push_success_count");
	}

	public M setPushFailCount(java.lang.Integer pushFailCount) {
		set("push_fail_count", pushFailCount);
		return (M)this;
	}
	
	public java.lang.Integer getPushFailCount() {
		return getInt("push_fail_count");
	}

	public M setReceiveType(java.lang.Integer receiveType) {
		set("receive_type", receiveType);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveType() {
		return getInt("receive_type");
	}

	public M setUsersType(java.lang.Integer usersType) {
		set("users_type", usersType);
		return (M)this;
	}
	
	public java.lang.Integer getUsersType() {
		return getInt("users_type");
	}

	public M setInstitutionId(java.lang.String institutionId) {
		set("institution_id", institutionId);
		return (M)this;
	}
	
	public java.lang.String getInstitutionId() {
		return getStr("institution_id");
	}

}
