package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLogType(java.lang.Integer logType) {
		set("log_type", logType);
		return (M)this;
	}
	
	public java.lang.Integer getLogType() {
		return getInt("log_type");
	}

	public M setOperObject(java.lang.String operObject) {
		set("oper_object", operObject);
		return (M)this;
	}
	
	public java.lang.String getOperObject() {
		return getStr("oper_object");
	}

	public M setOperTable(java.lang.String operTable) {
		set("oper_table", operTable);
		return (M)this;
	}
	
	public java.lang.String getOperTable() {
		return getStr("oper_table");
	}

	public M setOperId(java.lang.Integer operId) {
		set("oper_id", operId);
		return (M)this;
	}
	
	public java.lang.Integer getOperId() {
		return getInt("oper_id");
	}

	public M setOperType(java.lang.String operType) {
		set("oper_type", operType);
		return (M)this;
	}
	
	public java.lang.String getOperType() {
		return getStr("oper_type");
	}

	public M setOperRemark(java.lang.String operRemark) {
		set("oper_remark", operRemark);
		return (M)this;
	}
	
	public java.lang.String getOperRemark() {
		return getStr("oper_remark");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setCreateId(java.lang.Integer createId) {
		set("create_id", createId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateId() {
		return getInt("create_id");
	}

}
