package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopAttribute<M extends BaseShopAttribute<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品类型
	 */
	public M setAttributeCategoryId(java.lang.Long attributeCategoryId) {
		set("attribute_category_id", attributeCategoryId);
		return (M)this;
	}
	
	/**
	 * 商品类型
	 */
	public java.lang.Long getAttributeCategoryId() {
		return getLong("attribute_category_id");
	}

	/**
	 * 属性名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 属性名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 当添加商品时,该属性的添加类别; 0为手功输入;1为选择输入;2为多行文本输入
	 */
	public M setInputType(java.lang.Boolean inputType) {
		set("input_type", inputType);
		return (M)this;
	}
	
	/**
	 * 当添加商品时,该属性的添加类别; 0为手功输入;1为选择输入;2为多行文本输入
	 */
	public java.lang.Boolean getInputType() {
		return get("input_type");
	}

	/**
	 * 即选择输入,则attr_name对应的值的取值就是该这字段值 
	 */
	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	/**
	 * 即选择输入,则attr_name对应的值的取值就是该这字段值 
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}

}
