package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYjProcess<M extends BaseYjProcess<M>> extends Model<M> implements IBean {

	public M setProcessId(java.lang.Integer processId) {
		set("process_id", processId);
		return (M)this;
	}
	
	public java.lang.Integer getProcessId() {
		return getInt("process_id");
	}

	public M setProcessName(java.lang.String processName) {
		set("process_name", processName);
		return (M)this;
	}
	
	public java.lang.String getProcessName() {
		return getStr("process_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 1显示  0隐藏
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 1显示  0隐藏
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
