package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopProduct<M extends BaseShopProduct<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商品Id
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品Id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品规格ids
	 */
	public M setGoodsSpecificationIds(java.lang.String goodsSpecificationIds) {
		set("goods_specification_ids", goodsSpecificationIds);
		return (M)this;
	}
	
	/**
	 * 商品规格ids
	 */
	public java.lang.String getGoodsSpecificationIds() {
		return getStr("goods_specification_ids");
	}

	/**
	 * 商品序列号
	 */
	public M setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
		return (M)this;
	}
	
	/**
	 * 商品序列号
	 */
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	/**
	 * 商品编码
	 */
	public M setGoodsNumber(java.lang.Integer goodsNumber) {
		set("goods_number", goodsNumber);
		return (M)this;
	}
	
	/**
	 * 商品编码
	 */
	public java.lang.Integer getGoodsNumber() {
		return getInt("goods_number");
	}

	/**
	 * 零售价格
	 */
	public M setRetailPrice(java.math.BigDecimal retailPrice) {
		set("retail_price", retailPrice);
		return (M)this;
	}
	
	/**
	 * 零售价格
	 */
	public java.math.BigDecimal getRetailPrice() {
		return get("retail_price");
	}

	/**
	 * 价格
	 */
	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}
	
	/**
	 * 价格
	 */
	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

}
