package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopBrand<M extends BaseShopBrand<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 品牌名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 品牌名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 图片
	 */
	public M setListPicUrl(java.lang.String listPicUrl) {
		set("list_pic_url", listPicUrl);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getListPicUrl() {
		return getStr("list_pic_url");
	}

	/**
	 * 描述
	 */
	public M setSimpleDesc(java.lang.String simpleDesc) {
		set("simple_desc", simpleDesc);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getSimpleDesc() {
		return getStr("simple_desc");
	}

	/**
	 * 图片
	 */
	public M setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 排序
	 */
	public M setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}

	/**
	 * 显示
	 */
	public M setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	/**
	 * 显示
	 */
	public java.lang.Boolean getIsShow() {
		return get("is_show");
	}

	public M setFloorPrice(java.math.BigDecimal floorPrice) {
		set("floor_price", floorPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getFloorPrice() {
		return get("floor_price");
	}

	/**
	 * app显示图片
	 */
	public M setAppListPicUrl(java.lang.String appListPicUrl) {
		set("app_list_pic_url", appListPicUrl);
		return (M)this;
	}
	
	/**
	 * app显示图片
	 */
	public java.lang.String getAppListPicUrl() {
		return getStr("app_list_pic_url");
	}

	/**
	 * 新品牌
	 */
	public M setIsNew(java.lang.Boolean isNew) {
		set("is_new", isNew);
		return (M)this;
	}
	
	/**
	 * 新品牌
	 */
	public java.lang.Boolean getIsNew() {
		return get("is_new");
	}

	/**
	 * 图片
	 */
	public M setNewPicUrl(java.lang.String newPicUrl) {
		set("new_pic_url", newPicUrl);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getNewPicUrl() {
		return getStr("new_pic_url");
	}

	/**
	 * 排序
	 */
	public M setNewSortOrder(java.lang.Integer newSortOrder) {
		set("new_sort_order", newSortOrder);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getNewSortOrder() {
		return getInt("new_sort_order");
	}

}
