package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopCategoryclassfy<M extends BaseShopCategoryclassfy<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 规范名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 规范名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 排序
	 */
	public M setSortOrder(java.lang.Long sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Long getSortOrder() {
		return getLong("sort_order");
	}

	public M setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

}
