package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopAddress<M extends BaseShopAddress<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 会员ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 会员ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 收货人姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 手机
	 */
	public M setTelNumber(java.lang.String telNumber) {
		set("tel_number", telNumber);
		return (M)this;
	}
	
	/**
	 * 手机
	 */
	public java.lang.String getTelNumber() {
		return getStr("tel_number");
	}

	/**
	 * 邮编
	 */
	public M setPostalCode(java.lang.String postalCode) {
		set("postal_Code", postalCode);
		return (M)this;
	}
	
	/**
	 * 邮编
	 */
	public java.lang.String getPostalCode() {
		return getStr("postal_Code");
	}

	/**
	 * 收货地址国家码
	 */
	public M setNationalCode(java.lang.String nationalCode) {
		set("national_Code", nationalCode);
		return (M)this;
	}
	
	/**
	 * 收货地址国家码
	 */
	public java.lang.String getNationalCode() {
		return getStr("national_Code");
	}

	/**
	 * 省
	 */
	public M setProvinceName(java.lang.String provinceName) {
		set("province_Name", provinceName);
		return (M)this;
	}
	
	/**
	 * 省
	 */
	public java.lang.String getProvinceName() {
		return getStr("province_Name");
	}

	/**
	 * 市
	 */
	public M setCityName(java.lang.String cityName) {
		set("city_Name", cityName);
		return (M)this;
	}
	
	/**
	 * 市
	 */
	public java.lang.String getCityName() {
		return getStr("city_Name");
	}

	/**
	 * 区
	 */
	public M setCountyName(java.lang.String countyName) {
		set("county_Name", countyName);
		return (M)this;
	}
	
	/**
	 * 区
	 */
	public java.lang.String getCountyName() {
		return getStr("county_Name");
	}

	/**
	 * 详细收货地址信息
	 */
	public M setDetailInfo(java.lang.String detailInfo) {
		set("detail_Info", detailInfo);
		return (M)this;
	}
	
	/**
	 * 详细收货地址信息
	 */
	public java.lang.String getDetailInfo() {
		return getStr("detail_Info");
	}

	public M setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}
	
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

}
