package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopCategory<M extends BaseShopCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setFrontDesc(java.lang.String frontDesc) {
		set("front_desc", frontDesc);
		return (M)this;
	}
	
	public java.lang.String getFrontDesc() {
		return getStr("front_desc");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public M setSortOrder(java.lang.Long sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	public java.lang.Long getSortOrder() {
		return getLong("sort_order");
	}

	public M setShowIndex(java.lang.Integer showIndex) {
		set("show_index", showIndex);
		return (M)this;
	}
	
	public java.lang.Integer getShowIndex() {
		return getInt("show_index");
	}

	public M setIsShow(java.lang.Long isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	public java.lang.Long getIsShow() {
		return getLong("is_show");
	}

	/**
	 * 视频url
	 */
	public M setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
		return (M)this;
	}
	
	/**
	 * 视频url
	 */
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 赠送url
	 */
	public M setPresentUrl(java.lang.String presentUrl) {
		set("present_url", presentUrl);
		return (M)this;
	}
	
	/**
	 * 赠送url
	 */
	public java.lang.String getPresentUrl() {
		return getStr("present_url");
	}

	/**
	 * 背景
	 */
	public M setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}
	
	/**
	 * 背景
	 */
	public java.lang.String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 栏目封面
	 */
	public M setVideoImgUrl(java.lang.String videoImgUrl) {
		set("video_img_url", videoImgUrl);
		return (M)this;
	}
	
	/**
	 * 栏目封面
	 */
	public java.lang.String getVideoImgUrl() {
		return getStr("video_img_url");
	}

	/**
	 * 栏目封面
	 */
	public M setCoverUrl(java.lang.String coverUrl) {
		set("cover_url", coverUrl);
		return (M)this;
	}
	
	/**
	 * 栏目封面
	 */
	public java.lang.String getCoverUrl() {
		return getStr("cover_url");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setFrontName(java.lang.String frontName) {
		set("front_name", frontName);
		return (M)this;
	}
	
	public java.lang.String getFrontName() {
		return getStr("front_name");
	}

	/**
	 *  所属于哪个商品
	 */
	public M setGoodsId(java.lang.Long goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 *  所属于哪个商品
	 */
	public java.lang.Long getGoodsId() {
		return getLong("goods_id");
	}

	/**
	 * 分类id
	 */
	public M setClassfyId(java.lang.Integer classfyId) {
		set("classfy_id", classfyId);
		return (M)this;
	}
	
	/**
	 * 分类id
	 */
	public java.lang.Integer getClassfyId() {
		return getInt("classfy_id");
	}

}
