package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyAcceptProcess<M extends BaseJyAcceptProcess<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProcessId(java.lang.Integer processId) {
		set("process_id", processId);
		return (M)this;
	}
	
	public java.lang.Integer getProcessId() {
		return getInt("process_id");
	}

	public M setProcessName(java.lang.String processName) {
		set("process_name", processName);
		return (M)this;
	}
	
	public java.lang.String getProcessName() {
		return getStr("process_name");
	}

	public M setPartsId(java.lang.Integer partsId) {
		set("parts_id", partsId);
		return (M)this;
	}
	
	public java.lang.Integer getPartsId() {
		return getInt("parts_id");
	}

	/**
	 * 预计开工时间
	 */
	public M setPredictStart(java.util.Date predictStart) {
		set("predict_start", predictStart);
		return (M)this;
	}
	
	/**
	 * 预计开工时间
	 */
	public java.util.Date getPredictStart() {
		return get("predict_start");
	}

	/**
	 * 预计完工时间
	 */
	public M setPredictEnd(java.util.Date predictEnd) {
		set("predict_end", predictEnd);
		return (M)this;
	}
	
	/**
	 * 预计完工时间
	 */
	public java.util.Date getPredictEnd() {
		return get("predict_end");
	}

	/**
	 * 实际开工时间
	 */
	public M setRequireStart(java.util.Date requireStart) {
		set("require_start", requireStart);
		return (M)this;
	}
	
	/**
	 * 实际开工时间
	 */
	public java.util.Date getRequireStart() {
		return get("require_start");
	}

	/**
	 * 实际完工时间
	 */
	public M setRequireEnd(java.util.Date requireEnd) {
		set("require_end", requireEnd);
		return (M)this;
	}
	
	/**
	 * 实际完工时间
	 */
	public java.util.Date getRequireEnd() {
		return get("require_end");
	}

	/**
	 * 报工完成数量
	 */
	public M setRequireNumber(java.lang.Integer requireNumber) {
		set("require_number", requireNumber);
		return (M)this;
	}
	
	/**
	 * 报工完成数量
	 */
	public java.lang.Integer getRequireNumber() {
		return getInt("require_number");
	}

	/**
	 * 报废数量
	 */
	public M setScrapNumber(java.lang.Integer scrapNumber) {
		set("scrap_number", scrapNumber);
		return (M)this;
	}
	
	/**
	 * 报废数量
	 */
	public java.lang.Integer getScrapNumber() {
		return getInt("scrap_number");
	}

	/**
	 * 工序是否已完成 0未生产 1生产中 2已完工
	 */
	public M setStatus(java.lang.Integer Status) {
		set("_status", Status);
		return (M)this;
	}
	
	/**
	 * 工序是否已完成 0未生产 1生产中 2已完工
	 */
	public java.lang.Integer getStatus() {
		return getInt("_status");
	}

	public M setSuccessTime(java.util.Date successTime) {
		set("success_time", successTime);
		return (M)this;
	}
	
	public java.util.Date getSuccessTime() {
		return get("success_time");
	}

	public M setParentOrderId(java.lang.Integer parentOrderId) {
		set("parent_order_id", parentOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getParentOrderId() {
		return getInt("parent_order_id");
	}

	public M setParentPartsId(java.lang.Integer parentPartsId) {
		set("parent_parts_id", parentPartsId);
		return (M)this;
	}
	
	public java.lang.Integer getParentPartsId() {
		return getInt("parent_parts_id");
	}

	public M setParentProductId(java.lang.Integer parentProductId) {
		set("parent_product_id", parentProductId);
		return (M)this;
	}
	
	public java.lang.Integer getParentProductId() {
		return getInt("parent_product_id");
	}

	/**
	 * 0 删除 1显示
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 0 删除 1显示
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setAccount(java.lang.Integer account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.Integer getAccount() {
		return getInt("account");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setPrincipal(java.lang.String principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.lang.String getPrincipal() {
		return getStr("principal");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
