package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyClient<M extends BaseJyClient<M>> extends Model<M> implements IBean {

	public M setClientId(java.lang.Integer clientId) {
		set("client_id", clientId);
		return (M)this;
	}
	
	public java.lang.Integer getClientId() {
		return getInt("client_id");
	}

	/**
	 * 客户名
	 */
	public M setClientName(java.lang.String clientName) {
		set("client_name", clientName);
		return (M)this;
	}
	
	/**
	 * 客户名
	 */
	public java.lang.String getClientName() {
		return getStr("client_name");
	}

	/**
	 * 0 删除 1显示
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 0 删除 1显示
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setAccount(java.lang.Integer account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.Integer getAccount() {
		return getInt("account");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}

}
