package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopOrderReciver<M extends BaseShopOrderReciver<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 他自己的id
	 */
	public M setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}
	
	/**
	 * 他自己的id
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 收货人id
	 */
	public M setReceiverId(java.lang.Integer receiverId) {
		set("receiver_id", receiverId);
		return (M)this;
	}
	
	/**
	 * 收货人id
	 */
	public java.lang.Integer getReceiverId() {
		return getInt("receiver_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 0待付款,101订单已取消102订单已删除201订单已付款 202  表示订单已经领取，300订单已发货301用户确认收货401退款402完成
	 */
	public M setOrderStatus(java.lang.Long orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	/**
	 * 0待付款,101订单已取消102订单已删除201订单已付款 202  表示订单已经领取，300订单已发货301用户确认收货401退款402完成
	 */
	public java.lang.Long getOrderStatus() {
		return getLong("order_status");
	}

	/**
	 * 0待发货1已发货2已收货4退货
	 */
	public M setShippingStatus(java.lang.Long shippingStatus) {
		set("shipping_status", shippingStatus);
		return (M)this;
	}
	
	/**
	 * 0待发货1已发货2已收货4退货
	 */
	public java.lang.Long getShippingStatus() {
		return getLong("shipping_status");
	}

	/**
	 * 收件人
	 */
	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}
	
	/**
	 * 收件人
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 区县
	 */
	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}
	
	/**
	 * 区县
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 留言
	 */
	public M setPostscript(java.lang.String postscript) {
		set("postscript", postscript);
		return (M)this;
	}
	
	/**
	 * 留言
	 */
	public java.lang.String getPostscript() {
		return getStr("postscript");
	}

	/**
	 * 快递id
	 */
	public M setShippingId(java.lang.Integer shippingId) {
		set("shipping_id", shippingId);
		return (M)this;
	}
	
	/**
	 * 快递id
	 */
	public java.lang.Integer getShippingId() {
		return getInt("shipping_id");
	}

	/**
	 * 快递名称
	 */
	public M setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
		return (M)this;
	}
	
	/**
	 * 快递名称
	 */
	public java.lang.String getShippingName() {
		return getStr("shipping_name");
	}

	/**
	 * 运费额
	 */
	public M setShippingFee(java.math.BigDecimal shippingFee) {
		set("shipping_fee", shippingFee);
		return (M)this;
	}
	
	/**
	 * 运费额
	 */
	public java.math.BigDecimal getShippingFee() {
		return get("shipping_fee");
	}

	/**
	 * 运单号
	 */
	public M setShippingNo(java.lang.String shippingNo) {
		set("shipping_no", shippingNo);
		return (M)this;
	}
	
	/**
	 * 运单号
	 */
	public java.lang.String getShippingNo() {
		return getStr("shipping_no");
	}

	/**
	 * //新增时间
	 */
	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	/**
	 * //新增时间
	 */
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	/**
	 *  //确认时间
	 */
	public M setConfirmTime(java.util.Date confirmTime) {
		set("confirm_time", confirmTime);
		return (M)this;
	}
	
	/**
	 *  //确认时间
	 */
	public java.util.Date getConfirmTime() {
		return get("confirm_time");
	}

	/**
	 * ta的爱称
	 */
	public M setReceiverName(java.lang.String receiverName) {
		set("receiver_name", receiverName);
		return (M)this;
	}
	
	/**
	 * ta的爱称
	 */
	public java.lang.String getReceiverName() {
		return getStr("receiver_name");
	}

	/**
	 * 你的名字
	 */
	public M setSenderName(java.lang.String senderName) {
		set("sender_name", senderName);
		return (M)this;
	}
	
	/**
	 * 你的名字
	 */
	public java.lang.String getSenderName() {
		return getStr("sender_name");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	/**
	 * 0未填写收货地址 1已填写
	 */
	public M setIsLocation(java.lang.Integer isLocation) {
		set("is_location", isLocation);
		return (M)this;
	}
	
	/**
	 * 0未填写收货地址 1已填写
	 */
	public java.lang.Integer getIsLocation() {
		return getInt("is_location");
	}

}
