package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopGoodsAttribute<M extends BaseShopGoodsAttribute<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品Id
	 */
	public M setGoodsId(java.lang.Long goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品Id
	 */
	public java.lang.Long getGoodsId() {
		return getLong("goods_id");
	}

	/**
	 * 属性Id
	 */
	public M setAttributeId(java.lang.Long attributeId) {
		set("attribute_id", attributeId);
		return (M)this;
	}
	
	/**
	 * 属性Id
	 */
	public java.lang.Long getAttributeId() {
		return getLong("attribute_id");
	}

	/**
	 * 属性值
	 */
	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	/**
	 * 属性值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

}
