package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyReport<M extends BaseJyReport<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setPartsId(java.lang.Integer partsId) {
		set("parts_id", partsId);
		return (M)this;
	}
	
	public java.lang.Integer getPartsId() {
		return getInt("parts_id");
	}

	public M setProcessId(java.lang.Integer processId) {
		set("process_id", processId);
		return (M)this;
	}
	
	public java.lang.Integer getProcessId() {
		return getInt("process_id");
	}

	public M setParentProcessId(java.lang.Integer parentProcessId) {
		set("parent_process_id", parentProcessId);
		return (M)this;
	}
	
	public java.lang.Integer getParentProcessId() {
		return getInt("parent_process_id");
	}

	/**
	 * 报工时间
	 */
	public M setReportTime(java.util.Date reportTime) {
		set("report_time", reportTime);
		return (M)this;
	}
	
	/**
	 * 报工时间
	 */
	public java.util.Date getReportTime() {
		return get("report_time");
	}

	public M setRequireNumber(java.lang.Integer requireNumber) {
		set("require_number", requireNumber);
		return (M)this;
	}
	
	public java.lang.Integer getRequireNumber() {
		return getInt("require_number");
	}

	/**
	 * 报废数量
	 */
	public M setScrapNumber(java.lang.Integer scrapNumber) {
		set("scrap_number", scrapNumber);
		return (M)this;
	}
	
	/**
	 * 报废数量
	 */
	public java.lang.Integer getScrapNumber() {
		return getInt("scrap_number");
	}

	public M setDelectNumber(java.lang.Integer delectNumber) {
		set("delect_number", delectNumber);
		return (M)this;
	}
	
	public java.lang.Integer getDelectNumber() {
		return getInt("delect_number");
	}

	/**
	 * 报工账号
	 */
	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	/**
	 * 报工账号
	 */
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}

}
