package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopCoupon<M extends BaseShopCoupon<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 金额
	 */
	public M setTypeMoney(java.math.BigDecimal typeMoney) {
		set("type_money", typeMoney);
		return (M)this;
	}
	
	/**
	 * 金额
	 */
	public java.math.BigDecimal getTypeMoney() {
		return get("type_money");
	}

	public M setSendType(java.lang.Integer sendType) {
		set("send_type", sendType);
		return (M)this;
	}
	
	public java.lang.Integer getSendType() {
		return getInt("send_type");
	}

	/**
	 * 最小金额
	 */
	public M setMinAmount(java.math.BigDecimal minAmount) {
		set("min_amount", minAmount);
		return (M)this;
	}
	
	/**
	 * 最小金额
	 */
	public java.math.BigDecimal getMinAmount() {
		return get("min_amount");
	}

	/**
	 * 最大金额
	 */
	public M setMaxAmount(java.math.BigDecimal maxAmount) {
		set("max_amount", maxAmount);
		return (M)this;
	}
	
	/**
	 * 最大金额
	 */
	public java.math.BigDecimal getMaxAmount() {
		return get("max_amount");
	}

	public M setSendStartDate(java.util.Date sendStartDate) {
		set("send_start_date", sendStartDate);
		return (M)this;
	}
	
	public java.util.Date getSendStartDate() {
		return get("send_start_date");
	}

	public M setSendEndDate(java.util.Date sendEndDate) {
		set("send_end_date", sendEndDate);
		return (M)this;
	}
	
	public java.util.Date getSendEndDate() {
		return get("send_end_date");
	}

	public M setUseStartDate(java.util.Date useStartDate) {
		set("use_start_date", useStartDate);
		return (M)this;
	}
	
	public java.util.Date getUseStartDate() {
		return get("use_start_date");
	}

	public M setUseEndDate(java.util.Date useEndDate) {
		set("use_end_date", useEndDate);
		return (M)this;
	}
	
	public java.util.Date getUseEndDate() {
		return get("use_end_date");
	}

	/**
	 * 最小商品金额
	 */
	public M setMinGoodsAmount(java.math.BigDecimal minGoodsAmount) {
		set("min_goods_amount", minGoodsAmount);
		return (M)this;
	}
	
	/**
	 * 最小商品金额
	 */
	public java.math.BigDecimal getMinGoodsAmount() {
		return get("min_goods_amount");
	}

	/**
	 * 转发次数
	 */
	public M setMinTransmitNum(java.lang.Integer minTransmitNum) {
		set("min_transmit_num", minTransmitNum);
		return (M)this;
	}
	
	/**
	 * 转发次数
	 */
	public java.lang.Integer getMinTransmitNum() {
		return getInt("min_transmit_num");
	}

}
