package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopIndexImg<M extends BaseShopIndexImg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}
	
	public java.lang.String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 0 隐藏 1显示
	 */
	public M setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	/**
	 * 0 隐藏 1显示
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setShort(java.lang.Integer _short) {
		set("short", _short);
		return (M)this;
	}
	
	public java.lang.Integer getShort() {
		return getInt("short");
	}

}
