package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopConsumeLog<M extends BaseShopConsumeLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 订单id
	 */
	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单id
	 */
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 0 未成功 1 已完成
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 0 未成功 1 已完成
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 0 不显示 1显示
	 */
	public M setStatus(java.lang.Integer Status) {
		set("_status", Status);
		return (M)this;
	}
	
	/**
	 * 0 不显示 1显示
	 */
	public java.lang.Integer getStatus() {
		return getInt("_status");
	}

	/**
	 * 0 支出 1用户充值 2后台充值
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 0 支出 1用户充值 2后台充值
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 改变之前的钱包
	 */
	public M setBeforeMoney(java.lang.Double beforeMoney) {
		set("before_money", beforeMoney);
		return (M)this;
	}
	
	/**
	 * 改变之前的钱包
	 */
	public java.lang.Double getBeforeMoney() {
		return getDouble("before_money");
	}

	/**
	 * 用户实际收付的钱
	 */
	public M setChangeMoney(java.lang.Double changeMoney) {
		set("change_money", changeMoney);
		return (M)this;
	}
	
	/**
	 * 用户实际收付的钱
	 */
	public java.lang.Double getChangeMoney() {
		return getDouble("change_money");
	}

	/**
	 * 改变之后的钱包
	 */
	public M setAfterMoney(java.lang.Double afterMoney) {
		set("after_money", afterMoney);
		return (M)this;
	}
	
	/**
	 * 改变之后的钱包
	 */
	public java.lang.Double getAfterMoney() {
		return getDouble("after_money");
	}

}
