package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopUser<M extends BaseShopUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
		return (M)this;
	}
	
	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
		return (M)this;
	}
	
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	public M setUserLevelId(java.lang.Integer userLevelId) {
		set("user_level_id", userLevelId);
		return (M)this;
	}
	
	public java.lang.Integer getUserLevelId() {
		return getInt("user_level_id");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setRegisterIp(java.lang.String registerIp) {
		set("register_ip", registerIp);
		return (M)this;
	}
	
	public java.lang.String getRegisterIp() {
		return getStr("register_ip");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setWeixinOpenid(java.lang.String weixinOpenid) {
		set("weixin_openid", weixinOpenid);
		return (M)this;
	}
	
	public java.lang.String getWeixinOpenid() {
		return getStr("weixin_openid");
	}

	/**
	 * 钱包
	 */
	public M setMoney(java.lang.Double money) {
		set("money", money);
		return (M)this;
	}
	
	/**
	 * 钱包
	 */
	public java.lang.Double getMoney() {
		return getDouble("money");
	}

}
