package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopRechargeLog<M extends BaseShopRechargeLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 原来的钱
	 */
	public M setOrilMoney(java.lang.Double orilMoney) {
		set("oril_money", orilMoney);
		return (M)this;
	}
	
	/**
	 * 原来的钱
	 */
	public java.lang.Double getOrilMoney() {
		return getDouble("oril_money");
	}

	/**
	 * 变更之后的钱
	 */
	public M setChangeMoney(java.lang.Double changeMoney) {
		set("change_money", changeMoney);
		return (M)this;
	}
	
	/**
	 * 变更之后的钱
	 */
	public java.lang.Double getChangeMoney() {
		return getDouble("change_money");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 0隐藏 1显示
	 */
	public M setStatus(java.lang.Integer Status) {
		set("_status", Status);
		return (M)this;
	}
	
	/**
	 * 0隐藏 1显示
	 */
	public java.lang.Integer getStatus() {
		return getInt("_status");
	}

	/**
	 * 0 充值失败  1充值成功
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 0 充值失败  1充值成功
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
