package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 邮箱
	 */
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 手机号
	 */
	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 状态  0：禁用   1：正常
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态  0：禁用   1：正常
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建者ID
	 */
	public M setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建者ID
	 */
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 部门ID
	 */
	public M setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	/**
	 * 部门ID
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}
	
	public M setPlantName(java.lang.String plantName) {
		set("plant_name", plantName);
		return (M)this;
	}

	public java.lang.String getPlantName() {
		return getStr("plant_name");
	}

}
