package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRemain<M extends BaseSysRemain<M>> extends Model<M> implements IBean {

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public M setMessage(java.lang.Integer message) {
		set("message", message);
		return (M)this;
	}
	
	public java.lang.Integer getMessage() {
		return getInt("message");
	}

}
