package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopGoods<M extends BaseShopGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	public java.lang.Long getCategoryId() {
		return getLong("category_id");
	}

	public M setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
		return (M)this;
	}
	
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setBrandId(java.lang.Long brandId) {
		set("brand_id", brandId);
		return (M)this;
	}
	
	public java.lang.Long getBrandId() {
		return getLong("brand_id");
	}

	public M setGoodsNumber(java.lang.Integer goodsNumber) {
		set("goods_number", goodsNumber);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsNumber() {
		return getInt("goods_number");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	/**
	 * 简明介绍（商品详情图）
	 */
	public M setGoodsBrief(java.lang.String goodsBrief) {
		set("goods_brief", goodsBrief);
		return (M)this;
	}
	
	/**
	 * 简明介绍（商品详情图）
	 */
	public java.lang.String getGoodsBrief() {
		return getStr("goods_brief");
	}

	public M setGoodsDesc(java.lang.String goodsDesc) {
		set("goods_desc", goodsDesc);
		return (M)this;
	}
	
	public java.lang.String getGoodsDesc() {
		return getStr("goods_desc");
	}

	public M setIsOnSale(java.lang.Long isOnSale) {
		set("is_on_sale", isOnSale);
		return (M)this;
	}
	
	public java.lang.Long getIsOnSale() {
		return getLong("is_on_sale");
	}

	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	public M setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
		return (M)this;
	}
	
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}

	public M setIsDelete(java.lang.Long isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}
	
	public java.lang.Long getIsDelete() {
		return getLong("is_delete");
	}

	public M setAttributeCategory(java.lang.Long attributeCategory) {
		set("attribute_category", attributeCategory);
		return (M)this;
	}
	
	public java.lang.Long getAttributeCategory() {
		return getLong("attribute_category");
	}

	/**
	 * 专柜价格
	 */
	public M setCounterPrice(java.math.BigDecimal counterPrice) {
		set("counter_price", counterPrice);
		return (M)this;
	}
	
	/**
	 * 专柜价格
	 */
	public java.math.BigDecimal getCounterPrice() {
		return get("counter_price");
	}

	/**
	 * 附加价格
	 */
	public M setExtraPrice(java.math.BigDecimal extraPrice) {
		set("extra_price", extraPrice);
		return (M)this;
	}
	
	/**
	 * 附加价格
	 */
	public java.math.BigDecimal getExtraPrice() {
		return get("extra_price");
	}

	public M setIsNew(java.lang.Boolean isNew) {
		set("is_new", isNew);
		return (M)this;
	}
	
	public java.lang.Boolean getIsNew() {
		return get("is_new");
	}

	/**
	 * 商品单位
	 */
	public M setGoodsUnit(java.lang.String goodsUnit) {
		set("goods_unit", goodsUnit);
		return (M)this;
	}
	
	/**
	 * 商品单位
	 */
	public java.lang.String getGoodsUnit() {
		return getStr("goods_unit");
	}

	/**
	 * 商品主图
	 */
	public M setPrimaryPicUrl(java.lang.String primaryPicUrl) {
		set("primary_pic_url", primaryPicUrl);
		return (M)this;
	}
	
	/**
	 * 商品主图
	 */
	public java.lang.String getPrimaryPicUrl() {
		return getStr("primary_pic_url");
	}

	/**
	 * 商品列表图
	 */
	public M setListPicUrl(java.lang.String listPicUrl) {
		set("list_pic_url", listPicUrl);
		return (M)this;
	}
	
	/**
	 * 商品列表图
	 */
	public java.lang.String getListPicUrl() {
		return getStr("list_pic_url");
	}

	/**
	 * 零售价格
	 */
	public M setRetailPrice(java.math.BigDecimal retailPrice) {
		set("retail_price", retailPrice);
		return (M)this;
	}
	
	/**
	 * 零售价格
	 */
	public java.math.BigDecimal getRetailPrice() {
		return get("retail_price");
	}

	/**
	 * 销售量
	 */
	public M setSellVolume(java.lang.Long sellVolume) {
		set("sell_volume", sellVolume);
		return (M)this;
	}
	
	/**
	 * 销售量
	 */
	public java.lang.Long getSellVolume() {
		return getLong("sell_volume");
	}

	/**
	 * 主sku　product_id
	 */
	public M setPrimaryProductId(java.lang.Long primaryProductId) {
		set("primary_product_id", primaryProductId);
		return (M)this;
	}
	
	/**
	 * 主sku　product_id
	 */
	public java.lang.Long getPrimaryProductId() {
		return getLong("primary_product_id");
	}

	/**
	 * 单位价格，单价
	 */
	public M setUnitPrice(java.math.BigDecimal unitPrice) {
		set("unit_price", unitPrice);
		return (M)this;
	}
	
	/**
	 * 单位价格，单价
	 */
	public java.math.BigDecimal getUnitPrice() {
		return get("unit_price");
	}

	public M setPromotionDesc(java.lang.String promotionDesc) {
		set("promotion_desc", promotionDesc);
		return (M)this;
	}
	
	public java.lang.String getPromotionDesc() {
		return getStr("promotion_desc");
	}

	public M setPromotionTag(java.lang.String promotionTag) {
		set("promotion_tag", promotionTag);
		return (M)this;
	}
	
	public java.lang.String getPromotionTag() {
		return getStr("promotion_tag");
	}

	/**
	 * APP专享价
	 */
	public M setAppExclusivePrice(java.math.BigDecimal appExclusivePrice) {
		set("app_exclusive_price", appExclusivePrice);
		return (M)this;
	}
	
	/**
	 * APP专享价
	 */
	public java.math.BigDecimal getAppExclusivePrice() {
		return get("app_exclusive_price");
	}

	/**
	 * 是否是APP专属
	 */
	public M setIsAppExclusive(java.lang.Long isAppExclusive) {
		set("is_app_exclusive", isAppExclusive);
		return (M)this;
	}
	
	/**
	 * 是否是APP专属
	 */
	public java.lang.Long getIsAppExclusive() {
		return getLong("is_app_exclusive");
	}

	public M setIsLimited(java.lang.Long isLimited) {
		set("is_limited", isLimited);
		return (M)this;
	}
	
	public java.lang.Long getIsLimited() {
		return getLong("is_limited");
	}

	public M setIsHot(java.lang.Long isHot) {
		set("is_hot", isHot);
		return (M)this;
	}
	
	public java.lang.Long getIsHot() {
		return getLong("is_hot");
	}

	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	/**
	 * 创建人ID
	 */
	public M setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	/**
	 * 修改人ID
	 */
	public M setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 修改人ID
	 */
	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	/**
	 * 修改时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setCreateUserDeptId(java.lang.Long createUserDeptId) {
		set("create_user_dept_id", createUserDeptId);
		return (M)this;
	}
	
	public java.lang.Long getCreateUserDeptId() {
		return getLong("create_user_dept_id");
	}

}
