package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyRepertoryLog<M extends BaseJyRepertoryLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRepertoryId(java.lang.Integer repertoryId) {
		set("repertory_id", repertoryId);
		return (M)this;
	}
	
	public java.lang.Integer getRepertoryId() {
		return getInt("repertory_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setClientId(java.lang.Integer clientId) {
		set("client_id", clientId);
		return (M)this;
	}
	
	public java.lang.Integer getClientId() {
		return getInt("client_id");
	}

	public M setClientName(java.lang.String clientName) {
		set("client_name", clientName);
		return (M)this;
	}
	
	public java.lang.String getClientName() {
		return getStr("client_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public M setIsInvoice(java.lang.Integer isInvoice) {
		set("is_invoice", isInvoice);
		return (M)this;
	}
	
	public java.lang.Integer getIsInvoice() {
		return getInt("is_invoice");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}

}
