package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopOrder<M extends BaseShopOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}
	
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 收货人id
	 */
	public M setReceiverId(java.lang.Integer receiverId) {
		set("receiver_id", receiverId);
		return (M)this;
	}
	
	/**
	 * 收货人id
	 */
	public java.lang.Integer getReceiverId() {
		return getInt("receiver_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 0待付款,101订单已取消102订单已删除201订单已付款 202  表示订单已经领取，300订单已发货 301用户确认收货401退款402完成
	 */
	public M setOrderStatus(java.lang.Long orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	/**
	 * 0待付款,101订单已取消102订单已删除201订单已付款 202  表示订单已经领取，300订单已发货 301用户确认收货401退款402完成
	 */
	public java.lang.Long getOrderStatus() {
		return getLong("order_status");
	}

	/**
	 * 0待发货1已发货2已收货4退货
	 */
	public M setShippingStatus(java.lang.Long shippingStatus) {
		set("shipping_status", shippingStatus);
		return (M)this;
	}
	
	/**
	 * 0待发货1已发货2已收货4退货
	 */
	public java.lang.Long getShippingStatus() {
		return getLong("shipping_status");
	}

	/**
	 * 0待付款,1付款中,2已付款
	 */
	public M setPayStatus(java.lang.Long payStatus) {
		set("pay_status", payStatus);
		return (M)this;
	}
	
	/**
	 * 0待付款,1付款中,2已付款
	 */
	public java.lang.Long getPayStatus() {
		return getLong("pay_status");
	}

	/**
	 * 收件人
	 */
	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}
	
	/**
	 * 收件人
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 区县
	 */
	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}
	
	/**
	 * 区县
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 留言
	 */
	public M setPostscript(java.lang.String postscript) {
		set("postscript", postscript);
		return (M)this;
	}
	
	/**
	 * 留言
	 */
	public java.lang.String getPostscript() {
		return getStr("postscript");
	}

	/**
	 * 快递id
	 */
	public M setShippingId(java.lang.Integer shippingId) {
		set("shipping_id", shippingId);
		return (M)this;
	}
	
	/**
	 * 快递id
	 */
	public java.lang.Integer getShippingId() {
		return getInt("shipping_id");
	}

	/**
	 * 快递名称
	 */
	public M setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
		return (M)this;
	}
	
	/**
	 * 快递名称
	 */
	public java.lang.String getShippingName() {
		return getStr("shipping_name");
	}

	/**
	 * 运费额
	 */
	public M setShippingFee(java.math.BigDecimal shippingFee) {
		set("shipping_fee", shippingFee);
		return (M)this;
	}
	
	/**
	 * 运费额
	 */
	public java.math.BigDecimal getShippingFee() {
		return get("shipping_fee");
	}

	/**
	 * 运单号
	 */
	public M setShippingNo(java.lang.String shippingNo) {
		set("shipping_no", shippingNo);
		return (M)this;
	}
	
	/**
	 * 运单号
	 */
	public java.lang.String getShippingNo() {
		return getStr("shipping_no");
	}

	public M setPayId(java.lang.String payId) {
		set("pay_id", payId);
		return (M)this;
	}
	
	public java.lang.String getPayId() {
		return getStr("pay_id");
	}

	public M setPayName(java.lang.String payName) {
		set("pay_name", payName);
		return (M)this;
	}
	
	public java.lang.String getPayName() {
		return getStr("pay_name");
	}

	/**
	 * 实际需要支付的金额
	 */
	public M setActualPrice(java.math.BigDecimal actualPrice) {
		set("actual_price", actualPrice);
		return (M)this;
	}
	
	/**
	 * 实际需要支付的金额
	 */
	public java.math.BigDecimal getActualPrice() {
		return get("actual_price");
	}

	/**
	 * 积分
	 */
	public M setIntegral(java.lang.Long integral) {
		set("integral", integral);
		return (M)this;
	}
	
	/**
	 * 积分
	 */
	public java.lang.Long getIntegral() {
		return getLong("integral");
	}

	/**
	 * 积分钱
	 */
	public M setIntegralMoney(java.math.BigDecimal integralMoney) {
		set("integral_money", integralMoney);
		return (M)this;
	}
	
	/**
	 * 积分钱
	 */
	public java.math.BigDecimal getIntegralMoney() {
		return get("integral_money");
	}

	/**
	 * 订单总价
	 */
	public M setOrderPrice(java.math.BigDecimal orderPrice) {
		set("order_price", orderPrice);
		return (M)this;
	}
	
	/**
	 * 订单总价
	 */
	public java.math.BigDecimal getOrderPrice() {
		return get("order_price");
	}

	/**
	 * 商品总价
	 */
	public M setGoodsPrice(java.math.BigDecimal goodsPrice) {
		set("goods_price", goodsPrice);
		return (M)this;
	}
	
	/**
	 * 商品总价
	 */
	public java.math.BigDecimal getGoodsPrice() {
		return get("goods_price");
	}

	/**
	 * //新增时间
	 */
	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	/**
	 * //新增时间
	 */
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	/**
	 *  //确认时间
	 */
	public M setConfirmTime(java.util.Date confirmTime) {
		set("confirm_time", confirmTime);
		return (M)this;
	}
	
	/**
	 *  //确认时间
	 */
	public java.util.Date getConfirmTime() {
		return get("confirm_time");
	}

	/**
	 * //付款时间
	 */
	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}
	
	/**
	 * //付款时间
	 */
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	/**
	 * 配送费用
	 */
	public M setFreightPrice(java.lang.Long freightPrice) {
		set("freight_price", freightPrice);
		return (M)this;
	}
	
	/**
	 * 配送费用
	 */
	public java.lang.Long getFreightPrice() {
		return getLong("freight_price");
	}

	/**
	 * 使用的优惠券id
	 */
	public M setCouponId(java.lang.Integer couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}
	
	/**
	 * 使用的优惠券id
	 */
	public java.lang.Integer getCouponId() {
		return getInt("coupon_id");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 优惠价格
	 */
	public M setCouponPrice(java.math.BigDecimal couponPrice) {
		set("coupon_price", couponPrice);
		return (M)this;
	}
	
	/**
	 * 优惠价格
	 */
	public java.math.BigDecimal getCouponPrice() {
		return get("coupon_price");
	}

	public M setCallbackStatus(java.lang.String callbackStatus) {
		set("callback_status", callbackStatus);
		return (M)this;
	}
	
	public java.lang.String getCallbackStatus() {
		return getStr("callback_status");
	}

	public M setFullCutPrice(java.math.BigDecimal fullCutPrice) {
		set("full_cut_price", fullCutPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getFullCutPrice() {
		return get("full_cut_price");
	}

	/**
	 * "4"直接购买需要付款  “5”订单满减不需要付款
	 */
	public M setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
		return (M)this;
	}
	
	/**
	 * "4"直接购买需要付款  “5”订单满减不需要付款
	 */
	public java.lang.String getOrderType() {
		return getStr("order_type");
	}

	/**
	 * ta的爱称
	 */
	public M setReceiverName(java.lang.String receiverName) {
		set("receiver_name", receiverName);
		return (M)this;
	}
	
	/**
	 * ta的爱称
	 */
	public java.lang.String getReceiverName() {
		return getStr("receiver_name");
	}

	/**
	 * 你的名字
	 */
	public M setSenderName(java.lang.String senderName) {
		set("sender_name", senderName);
		return (M)this;
	}
	
	/**
	 * 你的名字
	 */
	public java.lang.String getSenderName() {
		return getStr("sender_name");
	}

	/**
	 * 祝福的id
	 */
	public M setBlessingname(java.lang.String blessingname) {
		set("blessingname", blessingname);
		return (M)this;
	}
	
	/**
	 * 祝福的id
	 */
	public java.lang.String getBlessingname() {
		return getStr("blessingname");
	}

	/**
	 * 所选分类的id
	 */
	public M setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	/**
	 * 所选分类的id
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

}
