package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysArea<M extends BaseSysArea<M>> extends Model<M> implements IBean {

	public M setIid(java.lang.Integer iid) {
		set("iid", iid);
		return (M)this;
	}
	
	public java.lang.Integer getIid() {
		return getInt("iid");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 1全部省份
2省份
3市
4县区
	 */
	public M setAreaType(java.lang.Integer areaType) {
		set("area_type", areaType);
		return (M)this;
	}
	
	/**
	 * 1全部省份
2省份
3市
4县区
	 */
	public java.lang.Integer getAreaType() {
		return getInt("area_type");
	}

	public M setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
		return (M)this;
	}
	
	public java.lang.String getAreaCode() {
		return getStr("area_code");
	}

	public M setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
		return (M)this;
	}
	
	public java.lang.String getAreaName() {
		return getStr("area_name");
	}

	public M setStatus(java.lang.Integer Status) {
		set("_status", Status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("_status");
	}

	public M setParentid(java.lang.String parentid) {
		set("parentid", parentid);
		return (M)this;
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	/**
	 * 区域邮编
	 */
	public M setAreaZip(java.lang.String areaZip) {
		set("area_zip", areaZip);
		return (M)this;
	}
	
	/**
	 * 区域邮编
	 */
	public java.lang.String getAreaZip() {
		return getStr("area_zip");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setVerdtm(java.util.Date verdtm) {
		set("verdtm", verdtm);
		return (M)this;
	}
	
	public java.util.Date getVerdtm() {
		return get("verdtm");
	}

	public M setAlphacode(java.lang.String alphacode) {
		set("alphacode", alphacode);
		return (M)this;
	}
	
	public java.lang.String getAlphacode() {
		return getStr("alphacode");
	}

	public M setPartnernum(java.lang.Integer partnernum) {
		set("partnernum", partnernum);
		return (M)this;
	}
	
	public java.lang.Integer getPartnernum() {
		return getInt("partnernum");
	}

}
