package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyRepertory<M extends BaseJyRepertory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	/**
	 * 库存
	 */
	public M setRepertoy(java.lang.Integer repertoy) {
		set("repertoy", repertoy);
		return (M)this;
	}
	
	/**
	 * 库存
	 */
	public java.lang.Integer getRepertoy() {
		return getInt("repertoy");
	}

	/**
	 * 剩余
	 */
	public M setResidue(java.lang.Integer residue) {
		set("residue", residue);
		return (M)this;
	}
	
	/**
	 * 剩余
	 */
	public java.lang.Integer getResidue() {
		return getInt("residue");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}

}
