package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopOrderGoods<M extends BaseShopOrderGoods<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单Id
	 */
	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单Id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 商品id
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品名称
	 */
	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 商品序列号
	 */
	public M setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
		return (M)this;
	}
	
	/**
	 * 商品序列号
	 */
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	/**
	 * 产品Id
	 */
	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	/**
	 * 产品Id
	 */
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	/**
	 * 商品数量
	 */
	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	/**
	 * 商品数量
	 */
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	/**
	 * 市场价
	 */
	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}
	
	/**
	 * 市场价
	 */
	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	/**
	 * 零售价格
	 */
	public M setRetailPrice(java.math.BigDecimal retailPrice) {
		set("retail_price", retailPrice);
		return (M)this;
	}
	
	/**
	 * 零售价格
	 */
	public java.math.BigDecimal getRetailPrice() {
		return get("retail_price");
	}

	/**
	 * 商品规格详情
	 */
	public M setGoodsSpecifitionNameValue(java.lang.String goodsSpecifitionNameValue) {
		set("goods_specifition_name_value", goodsSpecifitionNameValue);
		return (M)this;
	}
	
	/**
	 * 商品规格详情
	 */
	public java.lang.String getGoodsSpecifitionNameValue() {
		return getStr("goods_specifition_name_value");
	}

	/**
	 * 虚拟商品
	 */
	public M setIsReal(java.lang.Boolean isReal) {
		set("is_real", isReal);
		return (M)this;
	}
	
	/**
	 * 虚拟商品
	 */
	public java.lang.Boolean getIsReal() {
		return get("is_real");
	}

	/**
	 * 商品规格Ids
	 */
	public M setGoodsSpecifitionIds(java.lang.String goodsSpecifitionIds) {
		set("goods_specifition_ids", goodsSpecifitionIds);
		return (M)this;
	}
	
	/**
	 * 商品规格Ids
	 */
	public java.lang.String getGoodsSpecifitionIds() {
		return getStr("goods_specifition_ids");
	}

	/**
	 * 图片链接
	 */
	public M setListPicUrl(java.lang.String listPicUrl) {
		set("list_pic_url", listPicUrl);
		return (M)this;
	}
	
	/**
	 * 图片链接
	 */
	public java.lang.String getListPicUrl() {
		return getStr("list_pic_url");
	}

	public M setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public M setNumberRemain(java.lang.Integer numberRemain) {
		set("number_remain", numberRemain);
		return (M)this;
	}
	
	public java.lang.Integer getNumberRemain() {
		return getInt("number_remain");
	}

}
