package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJyAcceptParts<M extends BaseJyAcceptParts<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPartsId(java.lang.Integer partsId) {
		set("parts_id", partsId);
		return (M)this;
	}
	
	public java.lang.Integer getPartsId() {
		return getInt("parts_id");
	}

	public M setPartsName(java.lang.String partsName) {
		set("parts_name", partsName);
		return (M)this;
	}
	
	public java.lang.String getPartsName() {
		return getStr("parts_name");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setPartsNumber(java.lang.Integer partsNumber) {
		set("parts_number", partsNumber);
		return (M)this;
	}
	
	public java.lang.Integer getPartsNumber() {
		return getInt("parts_number");
	}

	/**
	 * 实际完成的数量
	 */
	public M setRequireNumber(java.lang.Integer requireNumber) {
		set("require_number", requireNumber);
		return (M)this;
	}
	
	/**
	 * 实际完成的数量
	 */
	public java.lang.Integer getRequireNumber() {
		return getInt("require_number");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 需要的工序
	 */
	public M setAcceptProcess(java.lang.String acceptProcess) {
		set("accept_process", acceptProcess);
		return (M)this;
	}
	
	/**
	 * 需要的工序
	 */
	public java.lang.String getAcceptProcess() {
		return getStr("accept_process");
	}

	public M setPredictStart(java.util.Date predictStart) {
		set("predict_start", predictStart);
		return (M)this;
	}
	
	public java.util.Date getPredictStart() {
		return get("predict_start");
	}

	public M setPredictEnd(java.util.Date predictEnd) {
		set("predict_end", predictEnd);
		return (M)this;
	}
	
	public java.util.Date getPredictEnd() {
		return get("predict_end");
	}

	public M setRequireStart(java.util.Date requireStart) {
		set("require_start", requireStart);
		return (M)this;
	}
	
	public java.util.Date getRequireStart() {
		return get("require_start");
	}

	public M setRequireEnd(java.util.Date requireEnd) {
		set("require_end", requireEnd);
		return (M)this;
	}
	
	public java.util.Date getRequireEnd() {
		return get("require_end");
	}

	/**
	 * 0未生产 1生产中 2已完工
	 */
	public M setStatus(java.lang.Integer Status) {
		set("_status", Status);
		return (M)this;
	}
	
	/**
	 * 0未生产 1生产中 2已完工
	 */
	public java.lang.Integer getStatus() {
		return getInt("_status");
	}

	public M setSuccessTime(java.util.Date successTime) {
		set("success_time", successTime);
		return (M)this;
	}
	
	public java.util.Date getSuccessTime() {
		return get("success_time");
	}

	/**
	 * 上级订单id
	 */
	public M setParentOrderId(java.lang.Integer parentOrderId) {
		set("parent_order_id", parentOrderId);
		return (M)this;
	}
	
	/**
	 * 上级订单id
	 */
	public java.lang.Integer getParentOrderId() {
		return getInt("parent_order_id");
	}

	/**
	 * 上级产品id
	 */
	public M setParentProductId(java.lang.Integer parentProductId) {
		set("parent_product_id", parentProductId);
		return (M)this;
	}
	
	/**
	 * 上级产品id
	 */
	public java.lang.Integer getParentProductId() {
		return getInt("parent_product_id");
	}

	/**
	 * 0删除 1显示
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 0删除 1显示
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setAccount(java.lang.Integer account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.Integer getAccount() {
		return getInt("account");
	}

	public M setPrincipal(java.lang.String principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.lang.String getPrincipal() {
		return getStr("principal");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public M setPlantId(java.lang.Integer plantId) {
		set("plant_id", plantId);
		return (M)this;
	}
	
	public java.lang.Integer getPlantId() {
		return getInt("plant_id");
	}

}
