package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public M setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	public java.lang.Long getMenuId() {
		return getLong("menu_id");
	}

	/**
	 * 父菜单ID，一级菜单为0
	 */
	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	/**
	 * 父菜单ID，一级菜单为0
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 菜单名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 菜单名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 菜单URL
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 菜单URL
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 授权(多个用逗号分隔，如：user:list,user:create)
	 */
	public M setPerms(java.lang.String perms) {
		set("perms", perms);
		return (M)this;
	}
	
	/**
	 * 授权(多个用逗号分隔，如：user:list,user:create)
	 */
	public java.lang.String getPerms() {
		return getStr("perms");
	}

	/**
	 * 类型   0：目录   1：菜单   2：按钮
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型   0：目录   1：菜单   2：按钮
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 菜单图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 菜单图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 排序
	 */
	public M setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
