package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysDept<M extends BaseSysDept<M>> extends Model<M> implements IBean {

	public M setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}

	/**
	 * 上级部门ID，一级部门为0
	 */
	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	/**
	 * 上级部门ID，一级部门为0
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 部门名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 排序
	 */
	public M setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

	/**
	 * 是否删除  -1：已删除  0：正常
	 */
	public M setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}
	
	/**
	 * 是否删除  -1：已删除  0：正常
	 */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

}
