package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbToken<M extends BaseTbToken<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * token
	 */
	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	/**
	 * token
	 */
	public java.lang.String getToken() {
		return getStr("token");
	}

	/**
	 * 过期时间
	 */
	public M setExpireTime(java.util.Date expireTime) {
		set("expire_time", expireTime);
		return (M)this;
	}
	
	/**
	 * 过期时间
	 */
	public java.util.Date getExpireTime() {
		return get("expire_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
