package cn.lhrj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUploadCounter<M extends BaseUploadCounter<M>> extends Model<M> implements IBean {

	public M setUploadType(java.lang.String uploadType) {
		set("uploadType", uploadType);
		return (M)this;
	}
	
	public java.lang.String getUploadType() {
		return getStr("uploadType");
	}

	public M setCounter(java.lang.Integer counter) {
		set("counter", counter);
		return (M)this;
	}
	
	public java.lang.Integer getCounter() {
		return getInt("counter");
	}

	public M setDescr(java.lang.String descr) {
		set("descr", descr);
		return (M)this;
	}
	
	public java.lang.String getDescr() {
		return getStr("descr");
	}

}
